from tornApi import TornAPI
from sections import Sections

api = TornAPI()
sections = Sections(api)
user = sections.user('')
# user_properties = user.properties.fetch_properties()
# print(user_properties.properties[0].property_data)
# property = sections.property(user_properties.properties[0].id)
# public_user= sections.user('123456')

# [print(ammo) for ammo in user.ammo.fetch_ammo()] 
# print(user.basic.fetch_basic())
# print(user.attacks.fetch_attacks())
# print(user.attacksfull.fetch_attacks_full())
# print(user.bars.fetch_bars())
# print(user.battlestats.fetch_battle_stats())
# print(user.bazaar.fetch_bazaar())
# print(user.cooldowns.fetch_cooldowns())
# print(user.crimes.fetch_crimes())
# print(user.criminal_record.fetch_record())
# print(user.discord.fetch_discord())
# print(user.display_items.fetch_display())
# print(user.education.fetch_education())
# print(user.equipment.fetch_equipment())
# print(user.events.fetch_events())
# print(user.gym.fetch_active_gym())
# print(user.hof.fetch_rankings())
# print(user.honors.fetch_honors())
# print(user.icons.fetch_icons())
# print(user.jobpoints.fetch_jobpoints())
# print(user.log.fetch_logs())
# print(user.lookup.fetch_selections())
# print(user.medals.fetch_medals())
# print(user.merits.fetch_merits())
# print(user.messages.fetch_messages())
# print(user.missions.fetch_missions())
# print(user.money.fetch_money())
# print(user.networth.fetch_networth())
# print(user.newevents.fetch_newevents())
# print(user.newmessages.fetch_newmessages())
# print(user.notifications.fetch_notifications())
# print(user.perks.fetch_perks())
# print(user.personalstats.fetch_stats())
# print(user.profile.fetch_profile())
# print(user.properties.fetch_properties())
# print(user.public_status.fetch_public_status())
# print(user.refills.fetch_refill_status())
# print(user.reports.fetch_last_reports())
# print(user.revives.fetch_latest_revives())
# print(user.revives_full.fetch_latest_revives_full())
# print(user.skills.fetch_skills())
# print(user.stocks.fetch_stocks())
# print(user.timestamp.fetch_current_timestamp())
# print(user.travel.fetch_travel_info())
# print(user.weapon_exp.fetch_weapon_exp())
# print(user.work_stats.fetch_work_stats())

# print(property.property.fetch_data())
api.close()